export const subCategoryList = [
    {
      id: 1,
      value: 'Leches',
      label: '🥛 Leches',
    },
    {
      id: 2,
      value: 'Yoghurt',
      label: '🥄 Yoghurt',
    },
    {
        id: 3,
        value: 'Quesos',
        label: '🧀 Quesos',
    },
  ];
  
  export const brandList = [
    {
      id: 1,
      value: 'Soprole',
      label: 'Soprole',
    },
    {
      id: 2,
      value: 'Lonco Leche',
      label: 'Lonco Leche',
    },
    {
      id: 3,
      value: 'Cuisine & Co',
      label: 'Cuisine & Co',
    },
    {
      id: 4,
      value: 'Colun',
      label: 'Colun',
    },
    {
      id: 5,
      value: 'Granorolo',
      label: 'Granorolo',
    },
  ];
  
  export const dataList = [
    {
      id: 1,
      title: 'Leche Descremada 1L',
      Brand: 'Soprole',
      category: 'lactios',
      subCategory: 'Leches',
      stock: 2,
      price: 2500,
      coverSrc: '/img/img1.jpg',
    },
    {
      id: 2,
      title: 'door urban',
      Brand: 'Lonco Leche',
      category: 'lactios',
      subCategory: 'Leches',
      stock: 5,
      price: 1000,
      coverSrc: '/img/img2.webp',
    },
    {
      id: 3,
      title: 'Leche Descremada 1L',
      Brand: 'Cuisine & Co',
      category: 'lactios',
      subCategory: 'Leches',
      stock: 6,
      price: 2000,
      coverSrc: '/img/img3.jpg',
    },
    {
      id: 4,
      title: 'Yoghurt Natural Endulzado',
      serviceTime: 'Colun',
      category: 'lactios',
      subCategory: 'Yoghurt',
      stock: 1,
      price: 1800,
      coverSrc: '/img/img4.jpg',
    },
    {
      id: 5,
      title: 'Yoghurt Natural No Endulzado',
      serviceTime: 'Colun',
      category: 'lactios',
      subCategory: 'Yoghurt',
      stock: 10,
      price: 2000,
      coverSrc: '/img/img5.jpg',
    },
    {
      id: 6,
      title: 'Queso Cheddar',
      Brand: 'Cuisine & Co',
      category: 'lactios',
      subCategory: 'Quesos',
      stock: 7,
      price: 3500,
      coverSrc: '/img/img6.jpg',
    },
    {
      id: 7,
      title: 'Queso Mozarrela',
      Brand: 'Granorolo',
      category: 'lactios',
      subCategory: 'Quesos',
      stock: 3,
      price: 2200,
      coverSrc: '/img/img7.jpg',
    },
    {
      id: 8,
      title: 'Queso Cammerbert',
      Brand: 'Quillayes',
      category: 'lactios',
      subCategory: 'Quesos',
      stock: 7,
      price: 1900,
      coverSrc: '/img/img8.jpg',
    },
    {
      id: 9,
      title: 'Queso Mantecoso',
      Brand: 'Cuisine & Co',
      category: 'lactios',
      subCategory: 'Quesos',
      stock: 7,
      price: 2750,
      coverSrc: '/img/img9.jpg',
    },
  ];